In [ ]:
from ultralytics import YOLO
import pandas as pd
import numpy as np

model = YOLO("yolov8n.pt")
results = model("/Users/aerilee/Desktop/Projects/cv_test/photos/53858b1c-af13-4721-92ad-524508c22d2a.jpg")
print(results[0].boxes)

image 1/1 /Users/aerilee/Desktop/Projects/cv_test/photos/53858b1c-af13-4721-92ad-524508c22d2a.jpg: 480x640 2 dogs, 27.0ms
Speed: 1.4ms preprocess, 27.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([16., 16.])
conf: tensor([0.8634, 0.8567])
data: tensor([[2.5806e+03, 1.2812e+03, 5.1118e+03, 3.4796e+03, 8.6339e-01, 1.6000e+01],
        [3.3663e+02, 6.9516e+02, 2.5743e+03, 3.1240e+03, 8.5668e-01, 1.6000e+01]])
id: None
is_track: False
orig_shape: (3840, 5120)
shape: torch.Size([2, 6])
xywh: tensor([[3846.1572, 2380.3989, 2531.2100, 2198.4678],
        [1455.4854, 1909.5790, 2237.7095, 2428.8401]])
xywhn: tensor([[0.7512, 0.6199, 0.4944, 0.5725],
        [0.2843, 0.4973, 0.4371, 0.6325]])
xyxy: tensor([[2580.5522, 1281.1652, 5111.7622, 3479.6328],
        [ 336.6306,  695.1589, 2574.3401, 3123.9990]])
xyxyn: tensor([[0.5040, 0.3336, 0.9984, 0.9062],
        [0.0657, 0.1810, 0.5028, 0.8135]])

In [5]:
photos_path = "/Users/aerilee/Desktop/Projects/cv_test/photos"
folder_result = model(photos_path, verbose=False)
result_table = []

for x in folder_result:                 # 사진 하나씩
    for box in x.boxes:                 # 그 사진의 상자 하나씩
        dic = {}
        dic["file_name"] = Path(x.path).name
        dic["cls_name"] = x.names[int(box.cls[0])]
        dic["conf"] = float(box.conf[0])
        x1, y1, x2, y2 = box.xyxy[0].tolist()
        dic["x1"], dic["y1"], dic["x2"], dic["y2"] = x1, y1, x2, y2
        result_table.append(dic)

df = pd.DataFrame(result_table)
df

,file_name,cls_name,conf,x1,y1,x2,y2
0,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,dog,0.930148,633.567932,860.686279,2627.208008,2619.336426
1,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,dog,0.922004,2579.744141,1612.845703,4193.005859,3537.049316
2,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,person,0.597965,85.211823,0.000000,1026.235962,2079.954102
3,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,banana,0.585581,4510.979980,2378.522949,4938.737793,2570.698730
4,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,chair,0.449832,0.890656,35.670898,471.761414,2516.286621
...,...,...,...,...,...,...,...
63,IMG_3914.jpeg,person,0.488162,594.064209,4844.589355,1641.303711,5709.682617
64,IMG_3914.jpeg,sandwich,0.343480,2495.782227,152.664948,4282.687500,3085.614258
65,IMG_3936.jpeg,cat,0.569940,1745.106567,3313.854980,4182.451172,4550.840332
66,IMG_3936.jpeg,dog,0.436064,1268.425903,1955.628662,3959.098145,3104.823486
67,IMG_3971.jpeg,dog,0.743252,32.623955,197.289505,3022.327393,4026.525146

In [6]:
df.groupby("cls_name").size()

cls_name
backpack         1
banana           1
bear             3
bed              3
bench            1
book             1
bottle           1
cat              2
chair            3
couch            6
dining table     1
dog             25
laptop           1
person           8
potted plant     2
sandwich         1
sheep            1
teddy bear       2
tv               2
vase             3
dtype: int64

In [8]:
df[df.conf > 0.5]

,file_name,cls_name,conf,x1,y1,x2,y2
0,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,dog,0.930148,633.567932,860.686279,2627.208008,2619.336426
1,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,dog,0.922004,2579.744141,1612.845703,4193.005859,3537.049316
2,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,person,0.597965,85.211823,0.000000,1026.235962,2079.954102
3,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,banana,0.585581,4510.979980,2378.522949,4938.737793,2570.698730
5,53858b1c-af13-4721-92ad-524508c22d2a.jpg,dog,0.863391,2580.552246,1281.165161,5111.762207,3479.632812
6,53858b1c-af13-4721-92ad-524508c22d2a.jpg,dog,0.856685,336.630615,695.158936,2574.340088,3123.999023
7,EFAA9501-DFD0-4E15-A65D-62B6BF688B13.jpg,person,0.887941,131.160568,1130.309326,326.584015,1558.870117
8,EFAA9501-DFD0-4E15-A65D-62B6BF688B13.jpg,person,0.847743,607.125854,1198.928589,843.250061,1645.520020
9,EFAA9501-DFD0-4E15-A65D-62B6BF688B13.jpg,person,0.797277,516.150818,1190.198120,627.414612,1605.950317
10,EFAA9501-DFD0-4E15-A65D-62B6BF688B13.jpg,backpack,0.712338,187.289825,1219.650146,292.057281,1374.269409
14,IMG_1542.jpeg,dog,0.810666,0.000000,25.865990,3023.153564,4016.141357
17,IMG_1639.jpeg,chair,0.651643,1317.913330,1042.982178,2347.867432,2058.910156
18,IMG_1639.jpeg,chair,0.586753,1.338712,663.736450,400.173889,2771.784668
19,IMG_1639.jpeg,dog,0.522780,1851.794312,1854.049927,2884.383545,2977.846924
26,IMG_1641.jpeg,dog,0.864487,5.926630,77.942116,2745.419434,4032.000000
27,IMG_1758.jpeg,dog,0.807874,4.278923,1197.627197,2972.389404,5666.967285
30,IMG_1760.jpeg,teddy bear,0.630868,4.946500,860.273254,3508.881592,5701.940918
32,IMG_1762.jpeg,teddy bear,0.682079,142.178177,880.636658,3479.407227,5692.814941
35,IMG_1764.jpeg,bed,0.532966,39.199947,4.003285,5696.513672,4284.000000
39,IMG_2157.jpeg,dog,0.710491,1535.863281,2320.169922,3853.928223,4304.855957
40,IMG_2157.jpeg,dog,0.581101,372.308167,1932.158447,2304.542969,4323.768066
43,IMG_2159.jpeg,dog,0.779299,1624.014648,1995.379150,3930.773682,4769.239746
44,IMG_2159.jpeg,dog,0.726948,369.439789,2077.935547,2136.197266,4734.180664
45,IMG_2159.jpeg,couch,0.579318,42.622814,3768.943115,4284.000000,5707.681152
48,IMG_2441.jpeg,laptop,0.908854,0.061235,2775.911377,855.462097,4029.196045
49,IMG_2441.jpeg,vase,0.642201,2042.733032,2477.015869,3020.244385,4028.116943
50,IMG_2441.jpeg,dog,0.568800,1020.439209,1054.505005,2871.198486,2610.942139
51,IMG_2656.jpeg,dog,0.864787,0.000000,1053.043579,2975.956055,4018.333984
52,IMG_2695.jpeg,dog,0.714572,5.407077,235.459518,3300.929443,5033.118164
55,IMG_3398.jpeg,vase,0.663977,1.293755,4037.465820,1619.470703,5707.335449
59,IMG_3873.jpeg,dog,0.797875,2814.833984,143.597229,5697.116699,3423.885010
60,IMG_3873.jpeg,dog,0.561736,174.865768,506.220001,3320.975098,2880.807373
61,IMG_3873.jpeg,bed,0.538803,15.858435,343.019684,5479.015137,4267.278809
65,IMG_3936.jpeg,cat,0.569940,1745.106567,3313.854980,4182.451172,4550.840332
67,IMG_3971.jpeg,dog,0.743252,32.623955,197.289505,3022.327393,4026.525146

In [9]:
df[df.conf < 0.5]

,file_name,cls_name,conf,x1,y1,x2,y2
4,2CFF8F8A-B59B-44A8-BFF7-4582F2201969.jpg,chair,0.449832,0.890656,35.670898,471.761414,2516.286621
11,EFAA9501-DFD0-4E15-A65D-62B6BF688B13.jpg,person,0.262666,345.096344,1017.690308,373.176514,1083.494141
12,IMG_1519.jpeg,dog,0.494881,0.732129,2.814665,4266.753418,5213.321777
13,IMG_1519.jpeg,bear,0.387652,0.000000,2.686107,4284.000000,5301.788086
15,IMG_1542.jpeg,bed,0.337653,11.684070,17.964073,3014.005127,3847.901855
16,IMG_1542.jpeg,sheep,0.286615,932.073303,2316.853760,3024.000000,4029.082520
20,IMG_1639.jpeg,potted plant,0.423481,94.484619,1.787688,932.750244,612.027466
21,IMG_1639.jpeg,dog,0.421484,274.784424,1795.085815,2915.517090,2901.906738
22,IMG_1639.jpeg,dog,0.346885,309.106537,1811.416382,1330.920776,2605.461670
23,IMG_1639.jpeg,bottle,0.283909,1798.149048,257.748871,1887.911377,593.787842
24,IMG_1639.jpeg,dining table,0.266672,2129.014160,553.388245,3021.287109,1943.390747
25,IMG_1639.jpeg,book,0.262394,2169.858887,545.627197,3021.733154,722.202881
28,IMG_1758.jpeg,couch,0.394304,4.247601,352.525513,4278.748047,5588.923828
29,IMG_1758.jpeg,person,0.258188,0.000000,346.554077,674.592041,2747.148682
31,IMG_1760.jpeg,couch,0.267044,7.429692,0.000000,4275.101074,5514.686523
33,IMG_1762.jpeg,couch,0.290707,22.639071,8.945700,4274.344727,4909.811035
34,IMG_1762.jpeg,person,0.280838,0.940526,782.264893,461.915131,2273.626221
36,IMG_1764.jpeg,dog,0.377016,995.562256,784.803528,5453.833984,3455.155762
37,IMG_2113.jpeg,dog,0.488420,186.122818,499.802917,3023.642578,4026.621094
38,IMG_2113.jpeg,cat,0.255429,176.393646,455.176910,3024.000000,4024.794678
41,IMG_2157.jpeg,dog,0.386517,356.396149,1939.624756,3991.853271,4333.936523
42,IMG_2157.jpeg,tv,0.340607,25.222767,2.923613,3283.252686,2351.453125
46,IMG_2159.jpeg,tv,0.265204,30.100903,0.000000,3407.218994,2462.739014
47,IMG_2159.jpeg,couch,0.255849,38.921314,2298.756836,4276.837402,5704.385742
53,IMG_2695.jpeg,couch,0.284149,29.250292,87.275864,4282.048340,5660.902832
54,IMG_2695.jpeg,bench,0.268602,0.000000,2492.656982,4279.194824,5703.896484
56,IMG_3398.jpeg,potted plant,0.401129,0.690184,0.000000,4167.115723,5662.395996
57,IMG_3468.jpeg,bear,0.457977,0.000000,1696.171143,3020.215576,4018.040283
58,IMG_3468.jpeg,bear,0.383357,0.000000,548.722595,3017.887207,3115.651855
62,IMG_3892.jpeg,vase,0.313882,1045.209839,3079.364014,3071.141113,4377.770996
63,IMG_3914.jpeg,person,0.488162,594.064209,4844.589355,1641.303711,5709.682617
64,IMG_3914.jpeg,sandwich,0.343480,2495.782227,152.664948,4282.687500,3085.614258
66,IMG_3936.jpeg,dog,0.436064,1268.425903,1955.628662,3959.098145,3104.823486